services:
  # Backend web service
  - type: web
    runtime: python
    name: stock-backend
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: TICKERS
        value: PLTR,NVDA,NEM

  # Static frontend site
  - type: web
    runtime: static
    name: stock-frontend
    rootDir: frontend
    buildCommand: |
      bash -lc '
        mkdir -p build &&
        cp -r . build &&
        echo "window.API_URL=\\"https://$RENDER_EXTERNAL_URL_stock-backend\\";" > build/config.js
      '
    staticPublishPath: build
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
