
services:
  - type: web
    name: stock-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: TICKERS
        value: PLTR,NVDA,NEM

  - type: static
    name: stock-frontend
    rootDir: frontend
    buildCommand: >
      bash -lc 'mkdir -p build && cp -r . build &&
      echo "window.API_URL=\"https://$RENDER_SERVICE_HOSTNAME_stock-backend\";" > build/config.js'
    staticPublishPath: build
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
